In [56]:
from pathlib import Path
import pandas as pd

def get_project_root():
    return Path().resolve().parent


df = pd.read_csv(get_project_root().parent / "HH+error_analysis_v2.csv", delimiter=";",dtype={"indicator_id": str})
#df = df[df['golden_label_update']=='x']

df_v3 = pd.read_csv(get_project_root().parent / "error_analysis_v3.csv",dtype={"indicator_id": str})

# df = df[df['golden_label_update']!='x'].dropna(subset='golden_label_update')
# with pd.option_context('display.max_rows', None):
#     display(df[['filename', 'indicator_id', 'golden_label_update']])

In [57]:
df[['fullname', 'filename', 'indicator_id', 'indicator_value', 'dimension',
       'golden_label', 'pred_label', 'value', 'pred_value', 'error_type',
       'evidence', 'rationale', 'golden_label_update', 'explanation']]

,fullname,filename,indicator_id,indicator_value,dimension,golden_label,pred_label,value,pred_value,error_type,evidence,rationale,golden_label_update,explanation
0,ACEH BIREUEN,ACEH_BIREUEN.txt,1.9,Sexual slavery / exploitation,scope_of_violence,Yes,No,1.0,0.0,false_negative,NaN,While exploitation is mentioned in employment ...,x,"Chapter 1, Article 1, no. 14 mentions special ..."
1,ACEH BIREUEN,ACEH_BIREUEN.txt,3.7,Psychosocial counselling,specialised_support_services,Yes,No,1.0,0.0,false_negative,NaN,"Although the policy references rehabilitation,...",x,"Paragraph 8, article 19, no.2 mentions psychol..."
2,ACEH BIREUEN,ACEH_BIREUEN.txt,4.2,Gender equality education,primary_prevention,No,Yes,0.0,1.0,false_positive,Article 5\n(1) Every woman has the right to:\n...,"The policy explicitly sets out women’s rights,...",x,NaN
3,ACEH BIREUEN,ACEH_BIREUEN.txt,4.4,Prevention through education,primary_prevention,No,Yes,0.0,1.0,false_positive,Article 25\n(1) The Regency Government is obli...,The policy includes prevention efforts through...,Yes,NaN
4,ACEH BIREUEN,ACEH_BIREUEN.txt,5.1,NGO collaboration,stakeholder_engagement,No,Yes,0.0,1.0,false_positive,CHAPTER VIII\nCOMMUNITY PARTICIPATION\nArticle...,The policy provides for community participatio...,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1084,SUMATERA UTARA PADANGSIDIMPUAN KOTA,SUMATERA_UTARA_PADANGSIDIMPUAN_KOTA.txt,6.3,Women workers,intersectional_approach,No,Yes,0.0,1.0,false_positive,Article 5\n(1) Every woman has the right to:\n...,The policy explicitly mentions work-related pr...,NaN,NaN
1085,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,1.9,Sexual slavery / exploitation,scope_of_violence,No,Yes,0.0,1.0,false_positive,Article 3\n(1) The objectives of providing pro...,The policy states an objective to eliminate al...,NaN,NaN
1086,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,3.1,Economic support services,specialised_support_services,Yes,No,1.0,0.0,false_negative,NaN,While prevention efforts mention access to tra...,NaN,NaN
1087,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,4.2,Gender equality education,primary_prevention,No,Yes,0.0,1.0,false_positive,CHAPTER XII\nCOMMUNITY PARTICIPATION\nArticle ...,The policy explicitly mentions community-led s...,NaN,NaN
1088,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,6.2,Trafficking victims,intersectional_approach,No,Yes,0.0,1.0,false_positive,Article 3\n(1) The objectives of providing pro...,The policy explicitly includes human trafficki...,NaN,NaN

In [58]:
df_v3[['fullname', 'filename', 'indicator_id', 'indicator_value', 'dimension',
       'golden_label', 'pred_label', 'value', 'pred_value', 'error_type',
       'evidence', 'rationale']]

,fullname,filename,indicator_id,indicator_value,dimension,golden_label,pred_label,value,pred_value,error_type,evidence,rationale
0,ACEH BIREUEN,ACEH_BIREUEN.txt,1.2,Sexual violence,scope_of_violence,Yes,No,1.0,0.0,false_negative,NaN,"The provided sentences refer generally to ""vio..."
1,ACEH BIREUEN,ACEH_BIREUEN.txt,5.4,Education institutions engagement,stakeholder_engagement,No,Yes,0.0,1.0,false_positive,"c. improve coordination, integration, synchron...",The policy includes “academics” among stakehol...
2,ACEH BIREUEN,ACEH_BIREUEN.txt,6.7,Women from minority groups,intersectional_approach,Yes,No,1.0,0.0,false_negative,NaN,While the general provisions define “Special P...
3,ACEH BIREUEN,ACEH_BIREUEN.txt,7.3,International donors,budget_funding_sources,No,Yes,0.0,1.0,false_positive,f. coordinating the participation of the busin...,The policy explicitly references coordinating ...
4,ACEH SUBULUSSALAM KOTA,ACEH_SUBULUSSALAM_KOTA.txt,1.2,Sexual violence,scope_of_violence,No,Yes,0.0,1.0,false_positive,NaN,The policy includes sexual violence both by re...
...,...,...,...,...,...,...,...,...,...,...,...,...
952,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,2.3,Data collection systems,institutional_mechanism,Yes,No,1.0,0.0,false_negative,NaN,The candidate sentences discuss establishing s...
953,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,3.7,Psychosocial counselling,specialised_support_services,Yes,No,1.0,0.0,false_negative,NaN,The candidate sentences mention health rehabil...
954,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,3.10,Economic support,specialised_support_services,Yes,No,1.0,0.0,false_negative,NaN,While the policy mentions broader prevention e...
955,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,4.2,Gender equality education,primary_prevention,No,Yes,0.0,1.0,false_positive,b. conduct socialization of women's and childr...,The policy includes a primary prevention-relat...
956,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,6.2,Women victims of trafficking,intersectional_approach,No,Yes,0.0,1.0,false_positive,a. prevent acts of violence against women and ...,The policy explicitly includes human trafficki...

In [59]:
import pandas as pd

# Columns that uniquely identify an example
merge_keys = [
    "fullname",
    "filename",
    "indicator_id",
]

# ------------------------------------------------------------------
# 1. Bring human review columns onto the new model output
# ------------------------------------------------------------------

human_cols = merge_keys + [
    "golden_label_update",
    "explanation",
]

df_v3 = df_v3.merge(
    df[human_cols],
    on=merge_keys,
    how="left",
)

# ------------------------------------------------------------------
# 2. Compare old vs new errors
# ------------------------------------------------------------------

old_errors = set(map(tuple, df[merge_keys].to_numpy()))
new_errors = set(map(tuple, df_v3[merge_keys].to_numpy()))

corrected = old_errors - new_errors      # error disappeared
new = new_errors - old_errors            # brand new error
persisting = old_errors & new_errors     # still an error

print(f"Old errors:        {len(old_errors)}")
print(f"New model errors:  {len(new_errors)}")
print(f"Corrected errors:  {len(corrected)}")
print(f"Persisting errors: {len(persisting)}")
print(f"New errors:        {len(new)}")

# ------------------------------------------------------------------
# 3. Create a summary dataframe
# ------------------------------------------------------------------

summary = pd.DataFrame({
    "Metric": [
        "Old errors",
        "New model errors",
        "Corrected by new model",
        "Persisting errors",
        "New errors introduced",
    ],
    "Count": [
        len(old_errors),
        len(new_errors),
        len(corrected),
        len(persisting),
        len(new),
    ]
})

print(summary)

# ------------------------------------------------------------------
# 4. (Optional) Label each row in df_v3
# ------------------------------------------------------------------

df_v3["_key"] = list(map(tuple, df_v3[merge_keys].to_numpy()))

df_v3["error_status"] = df_v3["_key"].map(
    lambda k: "Persisting error" if k in persisting else "New error"
)

df_v3.drop(columns="_key", inplace=True)

# ------------------------------------------------------------------
# 5. Save
# ------------------------------------------------------------------

df_v3.to_csv("df_v3_with_human_review.csv", index=False)
summary.to_csv("error_summary.csv", index=False)

Old errors:        1081
New model errors:  957
Corrected errors:  509
Persisting errors: 572
New errors:        385
                   Metric  Count
0              Old errors   1081
1        New model errors    957
2  Corrected by new model    509
3       Persisting errors    572
4   New errors introduced    385

In [60]:
merge_keys = ["fullname", "filename", "indicator_id"]

old_errors = set(map(tuple, df[merge_keys].to_numpy()))
new_errors = set(map(tuple, df_v3[merge_keys].to_numpy()))

corrected = old_errors - new_errors
persisting = old_errors & new_errors
new = new_errors - old_errors

old_df = df.copy()
new_df = df_v3.copy()

old_df["_key"] = list(map(tuple, old_df[merge_keys].to_numpy()))
new_df["_key"] = list(map(tuple, new_df[merge_keys].to_numpy()))

corrected_df = old_df[old_df["_key"].isin(corrected)].copy()
persisting_df = new_df[new_df["_key"].isin(persisting)].copy()
new_df_only = new_df[new_df["_key"].isin(new)].copy()

In [61]:
def summarise_by_indicator(df_):
    return (
        df_
        .groupby(["indicator_value", "indicator_id", "error_type"])
        .size()
        .unstack(fill_value=0)
        .assign(total=lambda x: x.sum(axis=1))
        .sort_values("total", ascending=False)
    )

corrected_summary = summarise_by_indicator(corrected_df)
persisting_summary = summarise_by_indicator(persisting_df)
new_summary = summarise_by_indicator(new_df_only)

In [62]:
summarise_by_indicator(df_v3).head(20).reset_index()

error_type,indicator_value,indicator_id,false_negative,false_positive,total
0,Prevention through education,4.4,2,90,92
1,Sexual slavery/exploitation,1.9,32,19,51
2,Women victims of trafficking,6.2,6,44,50
3,Gender equality education,4.2,8,36,44
4,Data collection systems,2.3,18,21,39
5,Training and capacity building,2.5,5,33,38
6,Traditional/cultural engagement,5.3,17,19,36
7,Education institutions engagement,5.4,7,23,30
8,Information and education about VAW,4.1,6,23,29
9,Women in legal process,6.8,1,27,28
10,Economic violence,1.5,26,2,28
11,People with disability,6.5,17,10,27
12,VAW laws awareness,4.3,15,11,26
13,Human trafficking,1.8,2,24,26
14,Harmful practices,1.6,8,17,25
15,Women workers,6.3,7,17,24
16,Economic support,3.10,4,19,23
17,Reporting/hotline service,3.3,14,7,21
18,Domestic violence,1.1,19,2,21
19,Media engagement,5.6,5,15,20

In [63]:
summarise_by_indicator(df_v3).head(20)['total'].sum()

np.int64(678)

In [64]:
corrected_summary

,error_type,false_negative,false_positive,total
indicator_value,indicator_id,,,
Institutional network / coordination mechanism,2.1,57,0,57
Gender equality education,4.2,3,38,41
Trafficking victims,6.2,34,5,39
Religious engagement,5.2,28,1,29
Disability,6.5,1,26,27
Economic support services,3.1,3,22,25
Prevention through education,4.4,0,23,23
Training and capacity building,2.5,9,13,22
Religious / spiritual counselling,3.8,14,2,16
Legal process involvement,6.8,0,15,15
Reporting / hotline,3.3,13,0,13
Traditional/cultural engagement,5.3,12,0,12
Refugees / displacement,6.1,0,11,11
Human trafficking,1.8,7,3,10
Media engagement,5.6,9,1,10
Data collection / information systems,2.3,5,4,9
Education institutions engagement,5.4,6,3,9
Gender mainstreaming institutionalisation,2.4,4,5,9
Police specialised service unit,3.2,2,7,9
Technology-facilitated violence,1.1,0,8,8
Harmful practices,1.6,1,7,8
Information & education on VAW,4.1,2,5,7
Private sector engagement,5.8,7,0,7
Sexual slavery / exploitation,1.9,1,6,7
Psychosocial counselling,3.7,7,0,7
International organisations engagement,5.5,2,5,7
Women workers,6.3,0,7,7
Provincial government budget,7.5,0,6,6
Economic violence,1.5,4,2,6
Safety / protection shelter,3.4,3,3,6
Resocialisation services,3.9,5,0,5
Minority groups,6.7,1,4,5
VAW laws awareness,4.3,1,4,5
Sexual violence,1.2,3,1,4
Physical violence,1.3,4,0,4
Collaboration with non-government service providers,2.2,4,0,4
NGO collaboration,5.1,3,1,4
Women in crisis settings,6.1,1,3,4
Heads of household,6.6,1,1,2
Other legal sources,7.4,0,2,2
Integrated service unit,3.1,1,1,2
Domestic workers,6.11,0,2,2
Domestic violence,1.1,1,0,1
Indigenous groups,6.9,0,1,1
National government budget,7.2,0,1,1
International donors,7.3,0,1,1
Local government budget,7.1,0,1,1

In [65]:
persisting_summary.head(20)

,error_type,false_negative,false_positive,total
indicator_value,indicator_id,,,
Prevention through education,4.4,1,64,65
Sexual slavery/exploitation,1.9,17,19,36
Gender equality education,4.2,5,29,34
Training and capacity building,2.5,4,23,27
Information and education about VAW,4.1,3,21,24
Traditional/cultural engagement,5.3,17,5,22
Data collection systems,2.3,4,15,19
People with disability,6.5,9,10,19
Harmful practices,1.6,6,12,18
VAW laws awareness,4.3,7,11,18
Women workers,6.3,2,16,18
Women victims of trafficking,6.2,6,10,16
Human trafficking,1.8,2,14,16
Education institutions engagement,5.4,4,11,15
Reporting/hotline service,3.3,11,3,14
Religious/spiritual counselling,3.8,10,3,13
Domestic violence,1.1,11,2,13
Religious engagement,5.2,9,3,12
Economic violence,1.5,9,2,11
Women in legal process,6.8,0,11,11

In [66]:
new_summary.head(20)

,error_type,false_negative,false_positive,total
indicator_value,indicator_id,,,
Women victims of trafficking,6.2,0,34,34
Prevention through education,4.4,1,26,27
Economic support,3.10,4,19,23
Data collection systems,2.3,14,6,20
Women in legal process,6.8,1,16,17
Economic violence,1.5,17,0,17
Education institutions engagement,5.4,3,12,15
Sexual slavery/exploitation,1.9,15,0,15
Traditional/cultural engagement,5.3,0,14,14
Media engagement,5.6,0,11,11
Refugee/forced displacement,6.10,0,11,11
Training and capacity building,2.5,1,10,11
Gender equality education,4.2,3,7,10
Human trafficking,1.8,0,10,10
Police specialised service unit,3.2,10,0,10
Domestic violence,1.1,8,0,8
People with disability,6.5,8,0,8
VAW laws awareness,4.3,8,0,8
International donors,7.3,0,8,8
Technology facilitated violence,1.10,0,7,7

In [67]:
def investigate_indicator(indicator_id):
    cols = [
        "fullname",
        "filename",
        "indicator_id",
        "indicator_value",
        "error_type",
        "golden_label",
        "golden_label_update",
        "golden_evidence",
        "pred_label",
        "value",
        "pred_value",
        "explanation",
        "evidence",
        "rationale",
    ]

    persisting = (
        persisting_df[persisting_df["indicator_id"] == indicator_id]
        .copy()
        .assign(error_status="Persisting")
    )

    new = (
        new_df_only[new_df_only["indicator_id"] == indicator_id]
        .copy()
        .assign(error_status="New")
    )

    result = pd.concat([persisting, new], ignore_index=True)

    if result.empty:
        print(f"No persisting or new errors for indicator_id={indicator_id}")
        return result

    result["human_reviewed"] = result["golden_label_update"].notna()

    # Add blank column after golden_label
    result.insert(
        result.columns.get_loc("golden_label_update") + 1,
        "golden_evidence",
        ""
    )

    return result[
        ["error_status", "human_reviewed"] + cols
    ].sort_values(
        ["error_status", "error_type", "fullname", "filename"]
    )

In [68]:
top20 = summarise_by_indicator(df_v3).head(20).reset_index()['indicator_id'].values
top20

<ArrowStringArray>
[ '4.4',  '1.9',  '6.2',  '4.2',  '2.3',  '2.5',  '5.3',  '5.4',  '4.1',
  '6.8',  '1.5',  '6.5',  '4.3',  '1.8',  '1.6',  '6.3', '3.10',  '3.3',
  '1.1',  '5.6']
Length: 20, dtype: str

In [69]:
output_dir = get_project_root().parent

for ind_ in top20:
    review_df = investigate_indicator(ind_)
    review_df.to_csv(
        output_dir / f"error_analysis_{ind_}.csv",
        index=False
    )

In [79]:
a = investigate_indicator("1.8")
a=a[a['error_type']=='false_positive']
a['filename'].values

<ArrowStringArray>
[                                 'BALI_BANGLI.txt',
                           'JAWA_TENGAH_KLATEN.txt',
                         'JAWA_TENGAH_WONOGIRI.txt',
                        'JAWA_TIMUR_BOJONEGORO.txt',
                            'JAWA_TIMUR_JEMBER.txt',
                            'JAWA_TIMUR_MADIUN.txt',
                     'KALIMANTAN_BARAT_SANGGAU.txt',
    'KEPULAUAN_BANGKA_BELITUNG_BANGKA_BARAT_v2.txt',
     'KEPULAUAN_BANGKA_BELITUNG_BANGKA_SELATAN.txt',
                         'MALUKU_MALUKU_TENGAH.txt',
                           'JAWA_TIMUR_SUMENEP.txt',
                  'KALIMANTAN_BARAT_BENGKAYANG.txt',
                  'KALIMANTAN_SELATAN_TABALONG.txt',
 'KEPULAUAN_BANGKA_BELITUNG_PANGKALPINANG_KOTA.txt',
                       'KEPULAUAN_RIAU_KARIMUN.txt',
                 'MALUKU_UTARA_HALMAHERA_TIMUR.txt',
                    'MALUKU_UTARA_TERNATE_KOTA.txt',
            'NUSA_TENGGARA_BARAT_LOMBOK_TENGAH.txt',
         'NUSA_TENGGARA_BARAT_LOMBOK_TENGAH_v2.txt',
                   'SULAWESI_SELATAN_BULUKUMBA.txt',
               'SULAWESI_TENGAH_PARIGI_MOUTONG.txt',
                         'SULAWESI_TENGAH_POSO.txt',
  'SUMATERA_SELATAN_PENUKAL_ABAB_LEMATANG_ILIR.txt',
                     'SUMATERA_UTARA_BATU_BARA.txt']
Length: 24, dtype: str

In [71]:
merge_keys = ["fullname", "filename", "indicator_id"]

old_errors = set(map(tuple, df[merge_keys].to_numpy()))
new_errors = set(map(tuple, df_v3[merge_keys].to_numpy()))

df_v3["_key"] = list(map(tuple, df_v3[merge_keys].to_numpy()))

df_v3["error_status"] = df_v3["_key"].map(
    lambda k: "Persisting" if k in old_errors else "New"
)

df_v3.drop(columns="_key", inplace=True)

In [72]:
df_v3

,fullname,filename,indicator_id,indicator_value,dimension,golden_label,pred_label,value,pred_value,error_type,evidence,rationale,discrepancy_root_cause,golden_label_update,explanation,error_status
0,ACEH BIREUEN,ACEH_BIREUEN.txt,1.2,Sexual violence,scope_of_violence,Yes,No,1.0,0.0,false_negative,NaN,"The provided sentences refer generally to ""vio...",Reference only,NaN,NaN,New
1,ACEH BIREUEN,ACEH_BIREUEN.txt,5.4,Education institutions engagement,stakeholder_engagement,No,Yes,0.0,1.0,false_positive,"c. improve coordination, integration, synchron...",The policy includes “academics” among stakehol...,Reference only,x,NaN,Persisting
2,ACEH BIREUEN,ACEH_BIREUEN.txt,6.7,Women from minority groups,intersectional_approach,Yes,No,1.0,0.0,false_negative,NaN,While the general provisions define “Special P...,Reference only,x,Any mention of special protection for women fr...,Persisting
3,ACEH BIREUEN,ACEH_BIREUEN.txt,7.3,International donors,budget_funding_sources,No,Yes,0.0,1.0,false_positive,f. coordinating the participation of the busin...,The policy explicitly references coordinating ...,Reference only,x,NaN,Persisting
4,ACEH SUBULUSSALAM KOTA,ACEH_SUBULUSSALAM_KOTA.txt,1.2,Sexual violence,scope_of_violence,No,Yes,0.0,1.0,false_positive,NaN,The policy includes sexual violence both by re...,Reference only,No,NaN,Persisting
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,2.3,Data collection systems,institutional_mechanism,Yes,No,1.0,0.0,false_negative,NaN,The candidate sentences discuss establishing s...,Reference only,NaN,NaN,New
960,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,3.7,Psychosocial counselling,specialised_support_services,Yes,No,1.0,0.0,false_negative,NaN,The candidate sentences mention health rehabil...,Reference only,NaN,NaN,New
961,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,3.10,Economic support,specialised_support_services,Yes,No,1.0,0.0,false_negative,NaN,While the policy mentions broader prevention e...,Reference only,NaN,NaN,New
962,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,4.2,Gender equality education,primary_prevention,No,Yes,0.0,1.0,false_positive,b. conduct socialization of women's and childr...,The policy includes a primary prevention-relat...,Reference only,NaN,NaN,Persisting
963,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,6.2,Women victims of trafficking,intersectional_approach,No,Yes,0.0,1.0,false_positive,a. prevent acts of violence against women and ...,The policy explicitly includes human trafficki...,Reference only,NaN,NaN,Persisting

In [73]:
summarise_by_indicator(df_v3).head(20)

,error_type,false_negative,false_positive,total
indicator_value,indicator_id,,,
Prevention through education,4.4,2,90,92
Sexual slavery/exploitation,1.9,32,19,51
Women victims of trafficking,6.2,6,44,50
Gender equality education,4.2,8,36,44
Data collection systems,2.3,18,21,39
Training and capacity building,2.5,5,33,38
Traditional/cultural engagement,5.3,17,19,36
Education institutions engagement,5.4,7,23,30
Information and education about VAW,4.1,6,23,29
Women in legal process,6.8,1,27,28
Economic violence,1.5,26,2,28
People with disability,6.5,17,10,27
VAW laws awareness,4.3,15,11,26
Human trafficking,1.8,2,24,26
Harmful practices,1.6,8,17,25
Women workers,6.3,7,17,24
Economic support,3.10,4,19,23
Reporting/hotline service,3.3,14,7,21
Domestic violence,1.1,19,2,21
Media engagement,5.6,5,15,20

In [74]:
def diagnose_indicator(indicator_id):
    cols = [
        "fullname",
        "filename",
        "indicator_id",
        "indicator_value",
        "error_status",
        "error_type",
        "golden_label",
        "golden_label_update",
        "pred_label",
        "value",
        "pred_value",
        "explanation",
        "evidence",
        "rationale",
    ]

    result = (
        df_v3[df_v3["indicator_id"] == str(indicator_id)]
        .copy()
    )

    if result.empty:
        print(f"No current errors for indicator_id={indicator_id}")
        return result

    result["human_reviewed"] = result["golden_label_update"].notna()

    print(f"Indicator {indicator_id}")
    print(f"Current errors: {len(result)}")
    print()

    print("Status")
    print(result["error_status"].value_counts())
    print()

    print("Error type")
    print(result["error_type"].value_counts())
    print()

    print("Human reviewed")
    print(result["human_reviewed"].value_counts())
    print()

    return result[cols].sort_values(
        ["human_reviewed", "error_type", "error_status"],
        ascending=[False, True, True]
    )

In [75]:
display(investigate_indicator("4.4"))

,error_status,human_reviewed,fullname,filename,indicator_id,indicator_value,error_type,golden_label,golden_label_update,golden_evidence,pred_label,value,pred_value,explanation,evidence,rationale
75,New,False,JAWA TENGAH WONOSOBO,JAWA_TENGAH_WONOSOBO.txt,4.4,Prevention through education,false_negative,Yes,NaN,,No,1.0,0.0,NaN,NaN,The cited sentences include broad prevention e...
65,New,False,DI YOGYAKARTA SLEMAN,DI_YOGYAKARTA_SLEMAN.txt,4.4,Prevention through education,false_positive,No,NaN,,Yes,0.0,1.0,NaN,b. conducting education on anti-violence value...,The policy explicitly frames prevention as inc...
66,New,False,JAWA BARAT GARUT,JAWA_BARAT_GARUT.txt,4.4,Prevention through education,false_positive,No,NaN,,Yes,0.0,1.0,NaN,d. conducting socialization regarding laws and...,The prevention section explicitly includes soc...
67,New,False,JAWA BARAT KARAWANG,JAWA_BARAT_KARAWANG.txt,4.4,Prevention through education,false_positive,No,NaN,,Yes,0.0,1.0,NaN,(1) The Regent establishes policy programs and...,The policy explicitly aims to eliminate acts o...
68,New,False,JAWA TENGAH BANYUMAS,JAWA_TENGAH_BANYUMAS.txt,4.4,Prevention through education,false_positive,No,NaN,,Yes,0.0,1.0,NaN,"a. conducting communication, information, and ...",Education is explicitly listed as part of prev...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Persisting,False,SUMATERA SELATAN MUSI RAWAS,SUMATERA_SELATAN_MUSI_RAWAS.txt,4.4,Prevention through education,false_positive,No,NaN,,Yes,0.0,1.0,NaN,b. conducting education about anti-violence va...,The policy explicitly includes conducting educ...
61,Persisting,False,SUMATERA SELATAN OGAN KOMERING ULU SELATAN,SUMATERA_SELATAN_OGAN_KOMERING_ULU_SELATAN.txt,4.4,Prevention through education,false_positive,No,NaN,,Yes,0.0,1.0,NaN,b. developing child-friendly schools;,The policy includes an education-related preve...
62,Persisting,False,SUMATERA SELATAN PENUKAL ABAB LEMATANG ILIR,SUMATERA_SELATAN_PENUKAL_ABAB_LEMATANG_ILIR.txt,4.4,Prevention through education,false_positive,No,NaN,,Yes,0.0,1.0,NaN,f. providing critical education regarding the ...,Within the section on prevention of violence a...
63,Persisting,False,SUMATERA SELATAN PRABUMULIH KOTA,SUMATERA_SELATAN_PRABUMULIH_KOTA.txt,4.4,Prevention through education,false_positive,No,NaN,,Yes,0.0,1.0,NaN,Prevention of Acts of Violence against Women a...,The policy frames prevention of violence again...
64,Persisting,False,SUMATERA UTARA PADANGSIDIMPUAN KOTA,SUMATERA_UTARA_PADANGSIDIMPUAN_KOTA.txt,4.4,Prevention through education,false_positive,No,NaN,,Yes,0.0,1.0,NaN,e. providing critical education about the righ...,Education is explicitly included as part of pr...